ABC: add missing chain_context to VirtualMachineAPI's constructor.
This silences `mypy` error:

eth/chains/base.py:250: error: Unexpected keyword argument "chain_context" for "VirtualMachineAPI"
eth/abc.py:2270: note: "VirtualMachineAPI" defined here