xdist keeps trying to run in circle, embrace it
I had removed xdist, since these need to run in serial anyway.
Unfortunately, it produced fairly strange errors, like:

py37-wheel-cli runtests: commands[3] | pytest tests/trinity/integration/ -k trinity_cli
usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: -n tests/trinity/integration/
  inifile: /home/circleci/repo/pytest.ini
  rootdir: /home/circleci/repo
ERROR: InvocationError for command '/home/circleci/repo/.tox/py37-wheel-cli/bin/pytest -p no:xdist tests/trinity/integration/ -k trinity_cli' (exited with code 4)

I tried quite a few things, and ended up bailing. It works fine
by re-adding pytest-xdist as a requirement, and setting -n 1.