Avoid requesting duplicate bodies in regular sync
Especially if the block import is taking a long time, you end up with
headers that are in `ready_tasks()` but not imported yet. Before this
commit, the header syncer would just keep trying to import those headers
that are waiting to be imported, so we keep trying to download the block
bodies for them. Most annoying of all, we keep getting:

ValidationError: Cannot finish prereq BlockImportPrereqs.StoreBlockBodies of task ...

This commit fixes the issue by only attempting to download block bodies
if they aren't already in the OrderedTaskPreparation object.